"""initial

Revision ID: 85f1655dc71c
Revises: 
Create Date: 2026-06-11 14:58:46.092365
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '85f1655dc71c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_skills_agent_id'), 'agent_skills', ['agent_id'], unique=False)
    op.create_table('agent_store',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_store_agent_id'), 'agent_store', ['agent_id'], unique=False)
    op.create_table('delegations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_agent_id', sa.String(length=36), nullable=False),
    sa.Column('to_agent_id', sa.String(length=36), nullable=False),
    sa.Column('task_goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_from_agent_id'), 'delegations', ['from_agent_id'], unique=False)
    op.create_index(op.f('ix_delegations_to_agent_id'), 'delegations', ['to_agent_id'], unique=False)
    op.create_table('quotas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_cost_limit', sa.Float(), nullable=False),
    sa.Column('current_tokens', sa.Integer(), nullable=False),
    sa.Column('current_cost', sa.Float(), nullable=False),
    sa.Column('reset_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotas_agent_id'), 'quotas', ['agent_id'], unique=True)
    op.create_table('usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_agent_id'), 'usage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usage_created_at'), 'usage', ['created_at'], unique=False)
    op.add_column('api_keys', sa.Column('api_key_enc', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'api_key_enc')
    op.drop_index(op.f('ix_usage_created_at'), table_name='usage')
    op.drop_index(op.f('ix_usage_agent_id'), table_name='usage')
    op.drop_table('usage')
    op.drop_index(op.f('ix_quotas_agent_id'), table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_delegations_to_agent_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_from_agent_id'), table_name='delegations')
    op.drop_table('delegations')
    op.drop_index(op.f('ix_agent_store_agent_id'), table_name='agent_store')
    op.drop_table('agent_store')
    op.drop_index(op.f('ix_agent_skills_agent_id'), table_name='agent_skills')
    op.drop_table('agent_skills')
    # ### end Alembic commands ###
