from __future__ import annotations

AGENT_TEMPLATES: list[dict] = [
    {
        "name": "code-reviewer",
        "role": "reviewer",
        "description": "Kod inceleme ve kalite değerlendirmesi yapan ajan",
        "system_prompt": "You are an expert code reviewer. Analyze code for correctness, security, performance, and maintainability. Provide structured feedback with severity ratings.",
        "default_provider": "openai",
        "default_model": "gpt-4o",
        "suggested_tools": ["git", "file"],
        "assigned_skills": ["code_review"],
    },
    {
        "name": "doc-writer",
        "role": "writer",
        "description": "Teknik dokümantasyon ve API referansı yazan ajan",
        "system_prompt": "You are a skilled technical writer. Create clear, well-structured documentation with code examples. Adapt tone to the target audience.",
        "default_provider": "openai",
        "default_model": "gpt-4o",
        "suggested_tools": ["file"],
        "assigned_skills": ["doc_writer"],
    },
    {
        "name": "researcher",
        "role": "researcher",
        "description": "Web'den bilgi toplayan ve raporlayan ajan",
        "system_prompt": "You are a research assistant. Gather information from multiple sources, cross-reference facts, and produce structured summaries.",
        "default_provider": "openai",
        "default_model": "gpt-4o",
        "suggested_tools": ["web_search"],
        "assigned_skills": ["research"],
    },
    {
        "name": "tester",
        "role": "tester",
        "description": "Test senaryosu üreten ve kalite güvencesi sağlayan ajan",
        "system_prompt": "You are a QA engineer. Write comprehensive tests covering happy paths, edge cases, and error conditions using Arrange-Act-Assert pattern.",
        "default_provider": "openai",
        "default_model": "gpt-4o",
        "suggested_tools": ["file"],
        "assigned_skills": ["tester"],
    },
    {
        "name": "assistant",
        "role": "assistant",
        "description": "Genel amaçlı yardımcı ajan",
        "system_prompt": "You are a helpful assistant. Answer questions, solve problems, and help with tasks to the best of your ability.",
        "default_provider": "openai",
        "default_model": "gpt-4o",
        "suggested_tools": [],
        "assigned_skills": [],
    },
    {
        "name": "custom",
        "role": "custom",
        "description": "Özelleştirilebilir ajan şablonu",
        "system_prompt": "You are a custom agent. Follow the instructions provided by your creator.",
        "default_provider": "openai",
        "default_model": "gpt-4o",
        "suggested_tools": [],
        "assigned_skills": [],
    },
]
